package com.capgemini;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.Assert.assertEquals;

public class Pacto5Test extends PaginaPrincipalPactometro{

  @Test
  public void pacto5() {

    // 3 | click | css=#part-PNV > img | 
    botonPNV.click();
    // 4 | click | id=abst | 
    botonAbs.click();
    // 5 | assertElementNotPresent | id=#part-PNV | 
    {
      List<WebElement> elements = atributoPNV;
      assert(elements.size() == 0);
    }

    // System.out.println(botonPP.getAttribute("disabled"));
    Assertions.assertEquals("true", botonPNV.getAttribute("disabled"));


    // 7 | click | id=partidos | 
    partidos.click();
    // 8 | click | id=reset | 
    reset.click();
    // 9 | click | id=num-abst | 
    numabst.click();
    // 10 | click | id=num-abst | 
    numabst.click();
    // 11 | assertText | id=num-abst | 0
    assertEquals("0", numabst.getText());
    // 12 | click | id=noes | 
    noes.click();
  }
}
