package com.capgemini;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class TestPactometro2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\adomenec\\OneDrive - Capgemini\\Desktop\\chromedriver\\chromedriver.exe");
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofDays(10));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testPactometro2() {
    // Test name: testPactometro2
    // Step # | name | target | value
    // 1 | open | /pactometro/ | 
    driver.get("https://cursosdedesarrollo.com/pactometro/");
    // 2 | setWindowSize | 1059x667 | 
    driver.manage().window().setSize(new Dimension(1059, 667));
    // 3 | click | css=#part-PSOE > img | 
    driver.findElement(By.cssSelector("#part-PSOE > img")).click();
    // 4 | click | id=part-Podemos | 
    driver.findElement(By.id("part-Podemos")).click();
    // 5 | click | id=sies | 
    driver.findElement(By.id("sies")).click();

    // 6 | verifyElementPresent | id=num-sies |
    {
      List<WebElement> elements = driver.findElements(By.id("num-sies"));
      assert(elements.size() > 0);
    }
    // 7 | assertText | id=num-sies | 155
    assertEquals("155", driver.findElement(By.id("num-sies")).getText());
  }
}
