package com.capgemini;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class WkiTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\adomenec\\OneDrive - Capgemini\\Desktop\\chromedriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testWikipedia() {
    // Test name: wki
    // Step # | name | target | value
    // 1 | open | /wiki/Wikipedia:Portada | 
    driver.get("https://es.wikipedia.org/wiki/Wikipedia:Portada");
    // 2 | setWindowSize | 1058x666 | 
    driver.manage().window().setSize(new Dimension(1058, 666));
    // 3 | click | id=searchInput | 
    driver.findElement(By.id("searchInput")).click();
    // 4 | type | id=searchInput | luna
    driver.findElement(By.id("searchInput")).sendKeys("luna");
    // 5 | click | css=.suggestions-result-current | 
    driver.findElement(By.cssSelector(".suggestions-result-current")).click();
    // 6 | click | css=p:nth-child(4) | 
    driver.findElement(By.cssSelector("p:nth-child(4)")).click();
    // 7 | assertText | css=p:nth-child(4) > b | Luna
    assertEquals("Luna", driver.findElement(By.cssSelector("p:nth-child(4) > b")).getText());
  }
}
