package com.capgemini.paginacompleja;// Generated by Selenium IDE

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebElement;

import java.net.MalformedURLException;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class Pacto5Test extends PaginaConfigurada {

  PaginaPrincipalPactometro paginaPrincipal;

  @BeforeEach
  @Override
  public void setUp() throws MalformedURLException {
    super.setUp();
    paginaPrincipal = new PaginaPrincipalPactometro(getDriver());
  }

  @Test
  public void pacto5() {

    // 3 | click | css=#part-PNV > img | 
    paginaPrincipal.botonPNV.click();
    // 4 | click | id=abst | 
    paginaPrincipal.botonAbs.click();
    // 5 | assertElementNotPresent | id=#part-PNV | 
    {
      List<WebElement> elements = paginaPrincipal.atributoPNV;
      assert(elements.size() == 0);
    }

    // System.out.println(botonPP.getAttribute("disabled"));
    Assertions.assertEquals("true", paginaPrincipal.botonPNV.getAttribute("disabled"));

  
    // 7 | click | id=partidos | 
    paginaPrincipal.partidos.click();
    // 8 | click | id=reset | 
    paginaPrincipal.reset.click();
    // 9 | click | id=num-abst | 
    paginaPrincipal.numabst.click();
    // 10 | click | id=num-abst | 
    paginaPrincipal.numabst.click();
    // 11 | assertText | id=num-abst | 0
    assertEquals("0", paginaPrincipal.numabst.getText());
    // 12 | click | id=noes | 
    paginaPrincipal.noes.click();
  }
}
